### ISSUE TITLE
QSO on/off time behaviour

### ISSUE THREAD

**Issue by Vic152** [smurphboy/OARCLogger#17]
QSO on time

1. On time should automatically populate when new QSO is open
2. On time can be updated to current time by pressing Set QSO on
3. On time can be update "by hand" by manually entering values

QSO off time
1. Maybe automatically populated when QSO is saved?
2. Off time should be set by pressing Set QSO off
3. Off time can be update "by hand" by manually entering values

**Comment by smurphboy** [comment]
It's a bug in the javascript. It is setting the time when the page is loaded, not when the button is clicked. Easy to fix
