### ISSUE TITLE
Is it possible to associate an already created QSO with an event?

### ISSUE THREAD

**Issue by guitarpicva** [smurphboy/OARCLogger#20]
I can't find anything in the QSO edit screen or Logbook list that seems to support this.

**Comment by smurphboy** [comment]
Yes, edit the QSO and changed the selected events and save the QSO. Let me know if this works for you.

**Comment by guitarpicva** [comment]
i'll test that out now

**Comment by guitarpicva** [comment]
I think I see how you are doing this now.  "No Event" or "None" as a valid event choice would be helpful instead of the non-intuitive deletion of all events if you just want to look at the raw log.
