### ISSUE TITLE
Suggestion: Change "Submit Query" button text to "Save Now" or similar.

### ISSUE THREAD

**Issue by guitarpicva** [smurphboy/OARCLogger#21]
Not everyone understand the "Query" terminology, but we are conditioned to look for the text "SAVE".

**Comment by smurphboy** [comment]
Which page are you looking at? A URL or screenshot would help me find this.

**Comment by guitarpicva** [comment]
Most of the forms use a "Submit Query" button at the bottom.

**Comment by smurphboy** [comment]
Ahh understood. The default for a HTML Form button text is 'Submit' - it was Submit Query that was confusing me. 
I should have changed them all to Add / Edit now... Report any I've missed

**Comment by guitarpicva** [comment]
Wilco, thanks!
