### ISSUE TITLE
ADIF import problem

### ISSUE THREAD

**Issue by MartinCRichards** [smurphboy/OARCLogger#23]
Exported ADIF from QRZ.com contains <time_on:4>1206
Once imported it appears as 12:00:06
Sample file attached - the three FT4 QSOs were all similar, but the three FT8 calls with 11-something came in OK

[g6fji.298729.20230703121104.adi.txt](https://github.com/smurphboy/OARCLogger/files/11936735/g6fji.298729.20230703121104.adi.txt)

**Comment by smurphboy** [comment]
This should now be fixed. Can you retest?

**Comment by MartinCRichards** [comment]
Yes looks good now, thanks
