### ISSUE TITLE
Typo on QSO Entry form: Propogation instead of Propagation

### ISSUE THREAD

**Issue by MartinCRichards** [smurphboy/OARCLogger#27]
See title...

**Comment by MartinCRichards** [comment]
![image](https://github.com/smurphboy/OARCLogger/assets/134268304/6c3e94bd-1cb9-4e12-a76a-f323fd65afab)

**Comment by smurphboy** [comment]
Doh - should be fixed now?

**Comment by MartinCRichards** [comment]
Yep, sorted :-)
