### ISSUE TITLE
QSO Search: remember number of entries choice

### ISSUE THREAD

**Issue by MartinCRichards** [smurphboy/OARCLogger#28]
If I select 'show 50 entries', edit an entry and save it, I go back to only 10 entries - would be nice to come back to 50 :-)

**Comment by smurphboy** [comment]
Possible. Need to add stateSave: true to all table javascript. Will do it in slower time

**Comment by smurphboy** [comment]
This should now be done

**Comment by MartinCRichards** [comment]
Yes, looks good - thanks
