### ISSUE TITLE
Sorting by band is numeric rather by frequency

### ISSUE THREAD

**Issue by MartinCRichards** [smurphboy/OARCLogger#30]
If I sort QSOs by band, mentally I expect 160m - 10m, 6,4,2,70... ie from LF to UHF.  What I see is 15m, 2m, 30m, 40m, 6m, 70cm, 80m, ie alphanumeric.

No idea how hard this is to do - actually sort on hidden column?!

**Comment by smurphboy** [comment]
Ahhh, I see. Agreed, it should sort by band not the string value. I'll have a look, it should be possible.

**Comment by smurphboy** [comment]
This should now be fixed. Please check

**Comment by MartinCRichards** [comment]
Looks good, thanks
