### ISSUE TITLE
Manual QSO not working

### ISSUE THREAD

**Issue by Nutster2454** [smurphboy/OARCLogger#5]
When pressing add qso but not adding to qso list with callsign

**Comment by Nutster2454** [comment]
Filled in form press add qso went to page for callsign but no qso displayed. Picutre upload of qso filled in as what was tried to be summited.
![qso not uplaoding 1](https://user-images.githubusercontent.com/24573564/225435516-7d9011ba-bb1b-4c3e-9fda-0e1b1db2961d.png)
![qso not uplaoding 2](https://user-images.githubusercontent.com/24573564/225435519-7392fecf-e124-46c4-874b-f0d62bfaeab9.png)
![qso not uploading where it takes me](https://user-images.githubusercontent.com/24573564/225435524-184672e4-7252-4b72-a844-9a9955bdc50c.png)

**Comment by smurphboy** [comment]
Good spot, issue was that <callsign>/P was logged as _P. So adding _P as a callsign would show the QSO. i.e. it logged. 

Now fixed so /P works.

**Comment by Nutster2454** [comment]
All working now
