### ISSUE TITLE
button for gird to lat long on contact not working

### ISSUE THREAD

**Issue by Nutster2454** [smurphboy/OARCLogger#6]
Pressed grid to lat long button on qso for contact grid. nothing happened. no lat long 
![qso not uplaoding 2](https://user-images.githubusercontent.com/24573564/225436065-9d1065ef-4949-4bc7-aef3-7c77b4f8176a.png)

**Comment by smurphboy** [comment]
I should have disabled those buttons... I haven't put the .js to drive that in yet... will get there.
