### ISSUE TITLE
Minor issue when filling out qso in lower case

### ISSUE THREAD

**Issue by Nutster2454** [smurphboy/OARCLogger#7]
When uploaded it doesn't change and display in upper case. same with callsign and sota ref
![not changing qso to caps once uploaded](https://user-images.githubusercontent.com/24573564/225439936-4b3bcc05-6800-49c9-b604-2516acb5d702.png)

**Comment by smurphboy** [comment]
Yep - understood. Solution is to force UPPER() for callsigns and SOTA / POTA references. Will need something a little more slick for Maidenhead grids.

**Comment by smurphboy** [comment]
Should be fixed by that last commit. Pushed to live

**Comment by Nutster2454** [comment]
All fixed doesn't matter now if summit qso in lower case
